# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine: true
    # update docker
    - run: docker version
    - run: sudo service docker stop
    - run: curl -fsSL https://get.docker.com/ | sudo sh
    - run: docker version
    - run: ./test.sh
